project_name: arrt

before:
  hooks:
    - make build-ui

builds:
  - main: ./main.go
    binary: arrt
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/solo-io/arrt/cmd.Version={{.Version}}'
      - -X 'github.com/solo-io/arrt/cmd.GitCommit={{.Commit}}'
      - -X 'github.com/solo-io/arrt/cmd.BuildDate={{.Date}}'

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - QUICKSTART.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: solo-io
    name: arrt
  draft: false
  prerelease: auto

brews:
  - name: arrt
    homepage: https://github.com/solo-io/arrt
    description: "AI Registry and Runtime"
    license: MIT
    folder: Formula
    repository:
      owner: solo-io
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

